services:
  redis:
    image: arm32v7/redis:6-bullseye
    container_name: redis
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
  circuit:
    build: .
    privileged: true
    container_name: circuit
    network_mode: host
    command: ["python3", "-u", "circuit.py"]
    volumes:
      - .:/code
    depends_on:
      - redis
  update_ips:
    build: .
    container_name: update_ips
    network_mode: host
    command: ["python3", "-u", "update_ips.py"]
    volumes:
      - .:/code
    depends_on:
      - redis
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  redis-data:
    driver: local
  data:
    driver: local