services:
  redis:
    image: redislabs/redismod
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
  app:
    build: .
    container_name: app
    network_mode: host
    volumes:
      - .:/code
    depends_on:
      - redis
volumes:
  redis-data:
    driver: local
