services:
  redis:
    image: arm32v7/redis:6-bullseye
    container_name: redis
    hostname: redis
    volumes:
      - redis-data:/data
    # networks:
    #   - redis-net
    ports:
      - '6379:6379'
  circuit:
    build: .
    container_name: circuit
    command: ["python3", "-u", "circuit.py"]
    volumes:
      - .:/code
    # networks:
    #   - redis-net
    depends_on:
      - redis
  update_ips:
    build: .
    container_name: update_ips
    network_mode: host
    command: ["python3", "-u", "update_ips.py"]
    volumes:
      - .:/code
    depends_on:
      - redis
# networks:
#   redis-net:
volumes:
  redis-data:
    driver: local